# Generated by Django 5.1 on 2026-02-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre corto de la marca (ej: GM, CNR)', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único de la marca', max_length=20, unique=True, verbose_name='Código')),
                ('full_name', models.CharField(blank=True, help_text='Nombre legal o descriptivo completo', max_length=200, null=True, verbose_name='Nombre completo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'brand',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FailureTypeModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del tipo de falla (ej: Mecánicas)', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único del tipo de falla', max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de falla',
                'verbose_name_plural': 'Tipos de falla',
                'db_table': 'failure_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GOPModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la GOP (ej: GOP 1)', max_length=50, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único de la GOP', max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Guardia Operativa',
                'verbose_name_plural': 'Guardias Operativas',
                'db_table': 'gop',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceUnitModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Número de identificación de la unidad (ej: A904, U3001)', max_length=50, unique=True, verbose_name='Número')),
                ('unit_type', models.CharField(choices=[('locomotora', 'Locomotora'), ('coche_remolcado', 'Coche Remolcado'), ('coche_motor', 'Coche Motor')], max_length=20, verbose_name='Tipo de unidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Unidad de mantenimiento',
                'verbose_name_plural': 'Unidades de mantenimiento',
                'db_table': 'maintenance_unit',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='Número de legajo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
                'db_table': 'supervisor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainNumberModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Número del servicio (ej: 1234)', max_length=10, unique=True, verbose_name='Número de tren')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('route', models.CharField(blank=True, help_text='Recorrido del tren (ej: Constitución - La Plata)', max_length=200, null=True, verbose_name='Recorrido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Número de tren',
                'verbose_name_plural': 'Números de tren',
                'db_table': 'train_number',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AffectedSystemModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del sistema (ej: Motor Diésel)', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único del sistema', max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('failure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affected_systems', to='tickets.failuretypemodel', verbose_name='Tipo de falla')),
            ],
            options={
                'verbose_name': 'Sistema afectado',
                'verbose_name_plural': 'Sistemas afectados',
                'db_table': 'affected_system',
                'ordering': ['failure_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocomotiveModelModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del modelo (ej: GT22CW)', max_length=50, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único del modelo', max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locomotive_models', to='tickets.brandmodel', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo de locomotora',
                'verbose_name_plural': 'Modelos de locomotora',
                'db_table': 'locomotive_model',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RailcarClassModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la clase (ej: CPA)', max_length=50, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único de la clase', max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='railcar_classes', to='tickets.brandmodel', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Clase de coche remolcado',
                'verbose_name_plural': 'Clases de coche remolcado',
                'db_table': 'railcar_class',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LocomotiveModel',
            fields=[
                ('maintenance_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='locomotive', serialize=False, to='tickets.maintenanceunitmodel', verbose_name='Unidad de mantenimiento')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locomotives', to='tickets.brandmodel', verbose_name='Marca')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locomotives', to='tickets.locomotivemodelmodel', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Locomotora',
                'verbose_name_plural': 'Locomotoras',
                'db_table': 'locomotive',
            },
        ),
        migrations.CreateModel(
            name='MotorcoachModel',
            fields=[
                ('maintenance_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='motorcoach', serialize=False, to='tickets.maintenanceunitmodel', verbose_name='Unidad de mantenimiento')),
                ('configuration', models.CharField(help_text='Configuración de coches (ej: CM-CM, CM-R-CM)', max_length=50, verbose_name='Configuración')),
                ('car_count', models.PositiveSmallIntegerField(help_text='Número de coches en la formación', verbose_name='Cantidad de coches')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motorcoaches', to='tickets.brandmodel', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Coche motor',
                'verbose_name_plural': 'Coches motor',
                'db_table': 'motorcoach',
            },
        ),
        migrations.CreateModel(
            name='RailcarModel',
            fields=[
                ('maintenance_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='railcar', serialize=False, to='tickets.maintenanceunitmodel', verbose_name='Unidad de mantenimiento')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='railcars', to='tickets.brandmodel', verbose_name='Marca')),
                ('railcar_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='railcars', to='tickets.railcarclassmodel', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Coche remolcado',
                'verbose_name_plural': 'Coches remolcados',
                'db_table': 'railcar',
            },
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Número único del ticket (ej: 2024-001)', max_length=20, unique=True, verbose_name='Número de ticket')),
                ('date', models.DateField(help_text='Fecha de la avería', verbose_name='Fecha')),
                ('entry_type', models.CharField(choices=[('inmediato', 'Inmediato'), ('programado', 'Programado'), ('no', 'NO')], help_text='Inmediato, Programado o NO', max_length=20, verbose_name='Tipo de ingreso')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('reported_failure', models.TextField(help_text='Descripción de la falla reportada por el conductor', verbose_name='Falla denunciada')),
                ('work_order_number', models.CharField(blank=True, help_text='Número de Orden de Trabajo (opcional)', max_length=50, null=True, verbose_name='Número de OT')),
                ('notification_time', models.TimeField(blank=True, null=True, verbose_name='Hora de aviso')),
                ('intervention_time', models.TimeField(blank=True, null=True, verbose_name='Hora de intervención')),
                ('delivery_time', models.TimeField(blank=True, null=True, verbose_name='Hora de entrega')),
                ('observations', models.TextField(blank=True, help_text='Trabajo realizado / observaciones de la GOP', null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('affected_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.affectedsystemmodel', verbose_name='Sistema afectado')),
                ('failure_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.failuretypemodel', verbose_name='Tipo de falla')),
                ('gop', models.ForeignKey(help_text='Guardia Operativa que atiende el ticket', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.gopmodel', verbose_name='GOP')),
                ('maintenance_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.maintenanceunitmodel', verbose_name='Unidad de mantenimiento')),
                ('supervisor', models.ForeignKey(blank=True, help_text='Supervisor interviniente (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.supervisormodel', verbose_name='Supervisor')),
                ('train_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.trainnumbermodel', verbose_name='Número de tren')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['ticket_number'], name='ticket_ticket__457ce8_idx'), models.Index(fields=['date'], name='ticket_date_4c710e_idx'), models.Index(fields=['status'], name='ticket_status_e60204_idx'), models.Index(fields=['maintenance_unit'], name='ticket_mainten_837ce0_idx')],
            },
        ),
    ]
