# Generated by Django 5.1 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_ticketmodel_affected_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketmodel",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aceptada", "Aceptada"),
                    ("rechazada", "Rechazada"),
                    ("analisis", "Análisis"),
                ],
                help_text="Resultado cuando afectó al servicio",
                max_length=20,
                null=True,
                verbose_name="Resolución",
            ),
        ),
    ]
