# Generated by Django 5.1 on 2026-02-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_affectedsystemmodel_id_alter_brandmodel_id_and_more'),
        ('tickets', '0004_ticketmodel_resolution'),
    ]

    operations = [
    ]
