# Generated by Django 5.1 on 2026-02-27 13:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0006_alter_ticketmodel_entry_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LugarModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.IntegerField(
                        help_text="Código numérico del lugar (legacy)",
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Nombre completo del lugar",
                        max_length=100,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "short_desc",
                    models.CharField(
                        blank=True,
                        help_text="Código corto (ej: LP, TY, RE)",
                        max_length=10,
                        null=True,
                        verbose_name="Abreviatura",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Taller", "Taller"),
                            ("Estación", "Estación"),
                            ("Depósito", "Depósito"),
                            ("Desvío", "Desvío"),
                            ("Mesa", "Mesa"),
                            ("Línea", "Línea"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "revision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Reparacion", "Reparación"),
                            ("Alistamiento", "Alistamiento"),
                            ("-", "-"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de revisión",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lugar",
                "verbose_name_plural": "Lugares",
                "db_table": "lugar",
                "ordering": ["descripcion"],
            },
        ),
        migrations.CreateModel(
            name="NovedadModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_unit_code",
                    models.CharField(
                        blank=True,
                        help_text="Código original de la base legacy",
                        max_length=50,
                        null=True,
                        verbose_name="Código Unidad (Legacy)",
                    ),
                ),
                ("fecha_desde", models.DateField(verbose_name="Fecha Desde")),
                (
                    "fecha_hasta",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Hasta"),
                ),
                (
                    "fecha_estimada",
                    models.DateField(
                        blank=True,
                        help_text="Fecha estimada de finalización",
                        null=True,
                        verbose_name="Fecha Estimada",
                    ),
                ),
                (
                    "intervencion",
                    models.CharField(
                        choices=[
                            ("AL", "Alistamiento"),
                            ("AL5000", "Alistamiento 5000km"),
                            ("RA", "Reparación"),
                            ("DI", "Disponible"),
                            ("AB", "Revisión AB"),
                            ("ABC", "Revisión ABC"),
                            ("RG", "Reparación General"),
                            ("TOR", "Torneado"),
                            ("N1", "Nivel 1"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Intervención",
                    ),
                ),
                (
                    "legacy_lugar_codigo",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Código Lugar (Legacy)"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "is_legacy",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si fue importado de la base legacy",
                        verbose_name="Registro Legacy",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "lugar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="novedades",
                        to="tickets.lugarmodel",
                        verbose_name="Lugar",
                    ),
                ),
                (
                    "maintenance_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Locomotora o Coche Motor",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="novedades",
                        to="tickets.maintenanceunitmodel",
                        verbose_name="Unidad de Mantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Novedad",
                "verbose_name_plural": "Novedades",
                "db_table": "novedad",
                "ordering": ["-fecha_desde", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["fecha_desde"], name="novedad_fecha_d_f52441_idx"
                    ),
                    models.Index(
                        fields=["maintenance_unit"], name="novedad_mainten_2a4258_idx"
                    ),
                    models.Index(
                        fields=["intervencion"], name="novedad_interve_5467da_idx"
                    ),
                    models.Index(
                        fields=["legacy_unit_code"], name="novedad_legacy__782949_idx"
                    ),
                ],
            },
        ),
    ]
