# Generated by Django 5.1 on 2026-02-27 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_add_lugar_and_novedad_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervencionTipoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código del tipo de intervención (ej: AL, RA, AB)', max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción del tipo de intervención', max_length=100, verbose_name='Descripción')),
                ('clase', models.CharField(choices=[('REV', 'Revisión'), ('DET', 'Detención'), ('-', '-')], default='-', help_text='Clasificación: Revisión (REV) o Detención (DET)', max_length=10, verbose_name='Clase')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Intervención',
                'verbose_name_plural': 'Tipos de Intervención',
                'db_table': 'intervencion_tipo',
                'ordering': ['codigo'],
            },
        ),
        migrations.RenameIndex(
            model_name='novedadmodel',
            new_name='novedad_interve_01b5e1_idx',
            old_name='novedad_interve_5467da_idx',
        ),
        migrations.AddField(
            model_name='novedadmodel',
            name='legacy_intervencion_codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Intervención (Legacy)'),
        ),
        migrations.AlterField(
            model_name='novedadmodel',
            name='intervencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='tickets.intervenciontipomodel', verbose_name='Tipo de Intervención'),
        ),
    ]
