# Generated by Django 5.1 on 2026-02-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_add_intervencion_tipo_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='SupervisorModel',
        ),
    ]
