# Generated by Django 5.1 on 2026-03-07 00:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_seed_cycles_and_recipients'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lugaremailrecipientmodel',
            new_name='lugar_email_lugar_i_0df969_idx',
            old_name='lugar_emai_lugar_i_4d4b73_idx',
        ),
        migrations.RenameIndex(
            model_name='lugaremailrecipientmodel',
            new_name='lugar_email_email_5412f5_idx',
            old_name='lugar_emai_email_7c3b5c_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenancecyclemodel',
            new_name='maintenance_rolling_c9ea29_idx',
            old_name='maintenanc_rolling_5b0ce7_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenancecyclemodel',
            new_name='maintenance_interve_2277be_idx',
            old_name='maintenanc_interve_0b42c1_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceentrymodel',
            new_name='maintenance_entry_d_b37f30_idx',
            old_name='maintenanc_entry_d_7ad0b3_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceentrymodel',
            new_name='maintenance_mainten_e18723_idx',
            old_name='maintenanc_mainten_6ddc8a_idx',
        ),
        migrations.AlterField(
            model_name='lugaremailrecipientmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maintenancecyclemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maintenanceentrymodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
