# Generated by Django 5.1 on 2026-03-10 13:49

from django.db import migrations, models


def assign_category_from_unit_type(apps, schema_editor):
    """Assign rolling_stock_category based on unit_type."""
    MaintenanceUnitModel = apps.get_model("tickets", "MaintenanceUnitModel")

    for unit in MaintenanceUnitModel.objects.all():
        if unit.unit_type in ["locomotora", "coche_motor"]:
            unit.rolling_stock_category = "traccion"
        elif unit.unit_type == "coche_remolcado":
            unit.rolling_stock_category = "ccrr"
        unit.save(update_fields=["rolling_stock_category"])


def reverse_category_assignment(apps, schema_editor):
    """Reverse migration - set all to null."""
    MaintenanceUnitModel = apps.get_model("tickets", "MaintenanceUnitModel")
    MaintenanceUnitModel.objects.all().update(rolling_stock_category=None)


class Migration(migrations.Migration):
    dependencies = [
        (
            "tickets",
            "0014_rename_lugar_emai_lugar_i_4d4b73_idx_lugar_email_lugar_i_0df969_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceunitmodel",
            name="rolling_stock_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("traccion", "Tracción (Locomotoras + Coches Motor)"),
                    ("ccrr", "Coches Remolcados"),
                ],
                help_text="Tracción (locomotoras + coches motor) o Coches Remolcados",
                max_length=10,
                null=True,
                verbose_name="Categoría",
            ),
        ),
        migrations.RunPython(
            assign_category_from_unit_type, reverse_category_assignment
        ),
    ]
