# Generated by Django 5.1 on 2026-03-10 17:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0017_create_kilometrage_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kilometragerecordmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
