# Generated by Django 5.1 on 2026-03-18 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0018_alter_kilometragerecordmodel_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceEntryEmailDispatchModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Intentos"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, null=True, verbose_name="Error"),
                ),
                (
                    "windows_username",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Usuario Windows",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envio"
                    ),
                ),
                (
                    "to_recipients",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Destinatarios TO"
                    ),
                ),
                (
                    "cc_recipients",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Destinatarios CC"
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Asunto"),
                ),
                (
                    "body",
                    models.TextField(verbose_name="Cuerpo"),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, null=True, verbose_name="Cuerpo HTML"),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=models.deletion.PROTECT,
                        related_name="email_dispatches",
                        to="tickets.maintenanceentrymodel",
                        verbose_name="Ingreso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso - Envio de correo",
                "verbose_name_plural": "Ingresos - Envios de correo",
                "db_table": "maintenance_entry_email_dispatch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="maintenanceentryemaildispatchmodel",
            index=models.Index(
                fields=["status", "created_at"], name="maintenanc_status_7a5e1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceentryemaildispatchmodel",
            index=models.Index(fields=["entry"], name="maintenanc_entry_id_64d36c_idx"),
        ),
    ]
