# Generated by Django 5.1 on 2026-03-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_create_maintenance_entry_email_dispatch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maintenanceentryemaildispatchmodel',
            new_name='maintenance_status_e4eb71_idx',
            old_name='maintenanc_status_7a5e1c_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceentryemaildispatchmodel',
            new_name='maintenance_entry_i_7455b6_idx',
            old_name='maintenanc_entry_id_64d36c_idx',
        ),
    ]
