# Generated by Django 5.1 on 2026-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_maintenanceentryemaildispatchmodel_drafted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceentryemaildispatchmodel',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reclamacion'),
        ),
        migrations.AlterField(
            model_name='maintenanceentryemaildispatchmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('drafted', 'Drafted'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
