# Generated by Django 5.1 on 2026-03-26 17:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0022_maintenanceentryemaildispatchmodel_claimed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceentryemaildispatchmodel",
            name="origin_terminal_id",
            field=models.CharField(
                blank=True, max_length=36, null=True, verbose_name="Terminal de origen"
            ),
        ),
        migrations.AddField(
            model_name="maintenanceentryemaildispatchmodel",
            name="terminal_id",
            field=models.CharField(
                blank=True, max_length=36, null=True, verbose_name="ID de terminal"
            ),
        ),
        migrations.CreateModel(
            name="TrayTerminalModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "terminal_id",
                    models.CharField(
                        max_length=36, unique=True, verbose_name="ID de terminal"
                    ),
                ),
                (
                    "windows_username",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Usuario Windows",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nombre de host",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última conexión"
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="En línea"),
                ),
                (
                    "registration_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP de registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Terminal de bandeja",
                "verbose_name_plural": "Terminales de bandeja",
                "db_table": "tray_terminal",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["terminal_id"], name="tray_termin_termina_408d48_idx"
                    ),
                    models.Index(
                        fields=["is_online", "last_seen"],
                        name="tray_termin_is_onli_deb05f_idx",
                    ),
                ],
            },
        ),
    ]
