# Generated by Django 5.1 on 2026-03-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0023_add_terminal_routing"),
    ]

    operations = [
        migrations.AddField(
            model_name="novedadmodel",
            name="ingreso_generado",
            field=models.BooleanField(
                default=False,
                help_text="Indica si ya se generó el ingreso para esta novedad",
                verbose_name="Ingreso Generado",
            ),
        ),
    ]
