# Generated by Django 5.1 on 2026-03-27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0024_add_ingreso_generado"),
    ]

    operations = [
        migrations.CreateModel(
            name="WagonTypeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                        help_text="Código único del tipo (ej: BK, Hopper)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        verbose_name="Nombre",
                        help_text="Nombre descriptivo del tipo",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Activo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de vagón",
                "verbose_name_plural": "Tipos de vagón",
                "db_table": "wagon_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WagonModel",
            fields=[
                (
                    "maintenance_unit",
                    models.OneToOneField(
                        on_delete=models.CASCADE,
                        primary_key=True,
                        related_name="wagon",
                        serialize=False,
                        to="tickets.maintenanceunitmodel",
                        verbose_name="Unidad de mantenimiento",
                    ),
                ),
                (
                    "legacy_class",
                    models.CharField(
                        max_length=100,
                        blank=True,
                        null=True,
                        verbose_name="Clase legacy",
                        help_text="Clase original importada desde legacy",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=models.PROTECT,
                        related_name="wagons",
                        to="tickets.brandmodel",
                        verbose_name="Marca",
                    ),
                ),
                (
                    "wagon_type",
                    models.ForeignKey(
                        on_delete=models.PROTECT,
                        related_name="wagons",
                        to="tickets.wagontypemodel",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vagón",
                "verbose_name_plural": "Vagones",
                "db_table": "wagon",
            },
        ),
        migrations.AlterField(
            model_name="maintenanceunitmodel",
            name="unit_type",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("locomotora", "Locomotora"),
                    ("coche_remolcado", "Coche Remolcado"),
                    ("coche_motor", "Coche Motor"),
                    ("vagon", "Vagón"),
                ],
                verbose_name="Tipo de unidad",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceunitmodel",
            name="rolling_stock_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("traccion", "Tracción (Locomotoras + Coches Motor)"),
                    ("ccrr", "Coches Remolcados"),
                    ("carga", "Carga (Vagones)"),
                ],
                help_text=(
                    "Tracción (locomotoras + coches motor), Coches Remolcados o Carga"
                ),
                max_length=10,
                null=True,
                verbose_name="Categoría",
            ),
        ),
    ]
