# Generated by Django 5.1 on 2026-03-30 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_add_wagon_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugaremailrecipientmodel',
            name='unit_type',
            field=models.CharField(choices=[('locomotora', 'Locomotora'), ('coche_remolcado', 'Coche Remolcado'), ('coche_motor', 'Coche Motor'), ('vagon', 'Vagón')], max_length=20, verbose_name='Tipo de unidad'),
        ),
        migrations.AlterField(
            model_name='maintenancecyclemodel',
            name='rolling_stock_type',
            field=models.CharField(choices=[('locomotora', 'Locomotora'), ('coche_remolcado', 'Coche Remolcado'), ('coche_motor', 'Coche Motor'), ('vagon', 'Vagón')], max_length=20, verbose_name='Tipo de unidad'),
        ),
        migrations.AlterField(
            model_name='personalmodel',
            name='sector',
            field=models.CharField(choices=[('locomotora', 'Locomotoras'), ('coche_remolcado', 'Coches Remolcados'), ('vagon', 'Vagones')], help_text='Locomotoras, Coches Remolcados o Vagones', max_length=20, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='wagontypemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
