# Generated by Django 5.1 on 2026-03-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_alter_lugaremailrecipientmodel_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kilometragerecordmodel',
            name='km_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kilometraje'),
        ),
    ]
