# Generated by Django 5.1 on 2026-04-15 13:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0028_add_legacy_novedad_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitMaintenanceSnapshotModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "unit_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Número de unidad",
                    ),
                ),
                (
                    "last_rg_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha última RG / PS"
                    ),
                ),
                (
                    "km_since_rg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="KM desde última RG / PS",
                    ),
                ),
                (
                    "last_numeral_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código última numeral",
                    ),
                ),
                (
                    "last_numeral_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha última numeral"
                    ),
                ),
                (
                    "km_since_numeral",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="KM desde última numeral",
                    ),
                ),
                (
                    "last_rp_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código último RP",
                    ),
                ),
                (
                    "last_rp_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha último RP"
                    ),
                ),
                (
                    "km_since_rp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="KM desde último RP",
                    ),
                ),
                (
                    "last_abc_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Código última ABC / R6",
                    ),
                ),
                (
                    "last_abc_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha última ABC / R6"
                    ),
                ),
                (
                    "km_since_abc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="KM desde última ABC / R6",
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Calculado el"),
                ),
                (
                    "maintenance_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_snapshot",
                        to="tickets.maintenanceunitmodel",
                        verbose_name="Unidad de mantenimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de mantenimiento",
                "verbose_name_plural": "Snapshots de mantenimiento",
                "db_table": "unit_maintenance_snapshot",
            },
        ),
    ]
