# Generated by Django 5.1 on 2026-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0029_add_unit_maintenance_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="novedadmodel",
            name="observaciones_egreso",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observaciones Egreso"
            ),
        ),
        migrations.AlterField(
            model_name="novedadmodel",
            name="observaciones",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observaciones Ingreso"
            ),
        ),
    ]
